= clj-jasper

A Clojure library to work with Jasper Reports

image:https://img.shields.io/clojars/v/net.tbt-post/clj-jasper.svg[]
https://clojars.org/net.tbt-post/clj-jasper[Clojars Project]

== Usage

Add the following to your http://github.com/technomancy/leiningen[Leiningen's] `project.clj`:

.project.clj
[source,clojure]
----
[net.tbt-post/clj-jasper "0.0.11"]
----

.example.clj
[source, clojure]
----
(ns my-app.jasper
  (:require [clj-jasper.core :as jc]
            [clojure.java.io :as io]))

(defn render [name data properties]
  (binding [jc/*jr-templates-path* "my-templates"]
    (let [out (jc/data->report {:name (format "my-reports/%s" name)
                                :data data
                                :ops  properties})]
      {:status  200
       :headers {"Content-Type"        (:type out)
                 "Content-Disposition" (format "attachment; filename=\"%s\"" (:name out))
                 "Cache-Control"       "no-cache"}
       :body    (-> out :file io/input-stream)})))
----

== Notes and limitations

. Current implementation supports only PDF generations.
. There is a bug in JAXP/XERCES (derived from CLJ<-JR<-Digester) that prevent the use of a parser that contains a schema with a DTD.
. Well tested with Java versions:
.. OpenJDK 11.0.12
.. OpenJDK 15.0.1
.. GraalVM 19.3.6.r11
.. Corretto 8.322.06.1
. Version v0.0.9 and v0.0.10 may be runtime incompatible with uberjar build in some circumstances
. JasperReports is very dependent on the SAX parser and requires at least a basic X setup on the server in order to render.
. Default font have to be available in JVM
. Final app is very sensitive to AOT compilation so be careful

== License

Copyright &copy; 2018-2022

Distributed under the MIT License.
